/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.form;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Quản lý Tour");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        pnDiaDiem = new javax.swing.JPanel();
        lbDiaDiem = new javax.swing.JLabel();
        pnTour = new javax.swing.JPanel();
        lbTour = new javax.swing.JLabel();
        pnKhachHang = new javax.swing.JPanel();
        lbKhachHang = new javax.swing.JLabel();
        pnNhanVien = new javax.swing.JPanel();
        lbNhanVien = new javax.swing.JLabel();
        pnGoiTour = new javax.swing.JPanel();
        lbGoiTour = new javax.swing.JLabel();
        pnVaiTro = new javax.swing.JPanel();
        lbVaiTro = new javax.swing.JLabel();
        pnDoan = new javax.swing.JPanel();
        lbDoan = new javax.swing.JLabel();
        pnLoaiHinh = new javax.swing.JPanel();
        lbLoaiHinh = new javax.swing.JLabel();
        pnDichVu = new javax.swing.JPanel();
        lbDichVu = new javax.swing.JLabel();
        pnTimKiem = new javax.swing.JPanel();
        lbTimKiem = new javax.swing.JLabel();
        pnThoat = new javax.swing.JPanel();
        lbThoat = new javax.swing.JLabel();
        pnThongKe = new javax.swing.JPanel();
        lbThongKe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(52, 124, 164));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        lb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lb1.setForeground(new java.awt.Color(244, 244, 244));
        lb1.setText("PHẦN MỀM QUẢN LÝ TOUR ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        pnDiaDiem.setBackground(new java.awt.Color(44, 59, 66));
        pnDiaDiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnDiaDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnDiaDiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnDiaDiemMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnDiaDiemMousePressed(evt);
            }
        });

        lbDiaDiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDiaDiem.setForeground(new java.awt.Color(114, 135, 145));
        lbDiaDiem.setText("ĐỊA ĐIỂM");

        javax.swing.GroupLayout pnDiaDiemLayout = new javax.swing.GroupLayout(pnDiaDiem);
        pnDiaDiem.setLayout(pnDiaDiemLayout);
        pnDiaDiemLayout.setHorizontalGroup(
            pnDiaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiaDiemLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnDiaDiemLayout.setVerticalGroup(
            pnDiaDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDiaDiemLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbDiaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pnTour.setBackground(new java.awt.Color(44, 59, 66));
        pnTour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnTourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnTourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnTourMousePressed(evt);
            }
        });

        lbTour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTour.setForeground(new java.awt.Color(114, 135, 145));
        lbTour.setText("TOUR");

        javax.swing.GroupLayout pnTourLayout = new javax.swing.GroupLayout(pnTour);
        pnTour.setLayout(pnTourLayout);
        pnTourLayout.setHorizontalGroup(
            pnTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTourLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTour, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        pnTourLayout.setVerticalGroup(
            pnTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTourLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbTour, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pnKhachHang.setBackground(new java.awt.Color(44, 59, 66));
        pnKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnKhachHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnKhachHangMousePressed(evt);
            }
        });

        lbKhachHang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbKhachHang.setForeground(new java.awt.Color(114, 135, 145));
        lbKhachHang.setText("KHÁCH HÀNG");

        javax.swing.GroupLayout pnKhachHangLayout = new javax.swing.GroupLayout(pnKhachHang);
        pnKhachHang.setLayout(pnKhachHangLayout);
        pnKhachHangLayout.setHorizontalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnKhachHangLayout.setVerticalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pnNhanVien.setBackground(new java.awt.Color(44, 59, 66));
        pnNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnNhanVienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnNhanVienMousePressed(evt);
            }
        });

        lbNhanVien.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbNhanVien.setForeground(new java.awt.Color(114, 135, 145));
        lbNhanVien.setText("NHÂN VIÊN");

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNhanVienLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pnGoiTour.setBackground(new java.awt.Color(44, 59, 66));
        pnGoiTour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnGoiTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnGoiTourMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnGoiTourMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnGoiTourMousePressed(evt);
            }
        });

        lbGoiTour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbGoiTour.setForeground(new java.awt.Color(114, 135, 145));
        lbGoiTour.setText("GÓI TOUR");

        javax.swing.GroupLayout pnGoiTourLayout = new javax.swing.GroupLayout(pnGoiTour);
        pnGoiTour.setLayout(pnGoiTourLayout);
        pnGoiTourLayout.setHorizontalGroup(
            pnGoiTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGoiTourLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(lbGoiTour, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnGoiTourLayout.setVerticalGroup(
            pnGoiTourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGoiTourLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbGoiTour, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pnVaiTro.setBackground(new java.awt.Color(44, 59, 66));
        pnVaiTro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnVaiTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnVaiTroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnVaiTroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnVaiTroMousePressed(evt);
            }
        });

        lbVaiTro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbVaiTro.setForeground(new java.awt.Color(114, 135, 145));
        lbVaiTro.setText("VAI TRÒ NV");

        javax.swing.GroupLayout pnVaiTroLayout = new javax.swing.GroupLayout(pnVaiTro);
        pnVaiTro.setLayout(pnVaiTroLayout);
        pnVaiTroLayout.setHorizontalGroup(
            pnVaiTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnVaiTroLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(lbVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        pnVaiTroLayout.setVerticalGroup(
            pnVaiTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnVaiTroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pnDoan.setBackground(new java.awt.Color(44, 59, 66));
        pnDoan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnDoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnDoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnDoanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnDoanMousePressed(evt);
            }
        });

        lbDoan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDoan.setForeground(new java.awt.Color(114, 135, 145));
        lbDoan.setText("ĐOÀN");

        javax.swing.GroupLayout pnDoanLayout = new javax.swing.GroupLayout(pnDoan);
        pnDoan.setLayout(pnDoanLayout);
        pnDoanLayout.setHorizontalGroup(
            pnDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDoanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnDoanLayout.setVerticalGroup(
            pnDoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDoanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbDoan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pnLoaiHinh.setBackground(new java.awt.Color(44, 59, 66));
        pnLoaiHinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnLoaiHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnLoaiHinhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnLoaiHinhMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnLoaiHinhMousePressed(evt);
            }
        });

        lbLoaiHinh.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbLoaiHinh.setForeground(new java.awt.Color(114, 135, 145));
        lbLoaiHinh.setText("LOẠI HÌNH DL");

        javax.swing.GroupLayout pnLoaiHinhLayout = new javax.swing.GroupLayout(pnLoaiHinh);
        pnLoaiHinh.setLayout(pnLoaiHinhLayout);
        pnLoaiHinhLayout.setHorizontalGroup(
            pnLoaiHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoaiHinhLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbLoaiHinh)
                .addGap(28, 28, 28))
        );
        pnLoaiHinhLayout.setVerticalGroup(
            pnLoaiHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoaiHinhLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbLoaiHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pnDichVu.setBackground(new java.awt.Color(44, 59, 66));
        pnDichVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnDichVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnDichVuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnDichVuMousePressed(evt);
            }
        });

        lbDichVu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbDichVu.setForeground(new java.awt.Color(114, 135, 145));
        lbDichVu.setText("DỊCH VỤ");

        javax.swing.GroupLayout pnDichVuLayout = new javax.swing.GroupLayout(pnDichVu);
        pnDichVu.setLayout(pnDichVuLayout);
        pnDichVuLayout.setHorizontalGroup(
            pnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDichVuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnDichVuLayout.setVerticalGroup(
            pnDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDichVuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pnTimKiem.setBackground(new java.awt.Color(44, 59, 66));
        pnTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnTimKiem.setMinimumSize(new java.awt.Dimension(220, 80));
        pnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnTimKiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnTimKiemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnTimKiemMouseExited(evt);
            }
        });

        lbTimKiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTimKiem.setForeground(new java.awt.Color(114, 135, 145));
        lbTimKiem.setText("TÌM KIẾM");

        javax.swing.GroupLayout pnTimKiemLayout = new javax.swing.GroupLayout(pnTimKiem);
        pnTimKiem.setLayout(pnTimKiemLayout);
        pnTimKiemLayout.setHorizontalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnTimKiemLayout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(lbTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(52, Short.MAX_VALUE)))
        );
        pnTimKiemLayout.setVerticalGroup(
            pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
            .addGroup(pnTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnTimKiemLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(lbTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGap(23, 23, 23)))
        );

        pnThoat.setBackground(new java.awt.Color(44, 59, 66));
        pnThoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnThoat.setMinimumSize(new java.awt.Dimension(220, 80));
        pnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnThoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnThoatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnThoatMousePressed(evt);
            }
        });

        lbThoat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbThoat.setForeground(new java.awt.Color(114, 135, 145));
        lbThoat.setText("THOÁT");

        javax.swing.GroupLayout pnThoatLayout = new javax.swing.GroupLayout(pnThoat);
        pnThoat.setLayout(pnThoatLayout);
        pnThoatLayout.setHorizontalGroup(
            pnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThoatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        pnThoatLayout.setVerticalGroup(
            pnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnThongKe.setBackground(new java.awt.Color(44, 59, 66));
        pnThongKe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 94, 100), 2));
        pnThongKe.setMinimumSize(new java.awt.Dimension(220, 80));
        pnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnThongKeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnThongKeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnThongKeMousePressed(evt);
            }
        });

        lbThongKe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbThongKe.setForeground(new java.awt.Color(114, 135, 145));
        lbThongKe.setText("THỐNG KÊ");

        javax.swing.GroupLayout pnThongKeLayout = new javax.swing.GroupLayout(pnThongKe);
        pnThongKe.setLayout(pnThongKeLayout);
        pnThongKeLayout.setHorizontalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnThongKeLayout.setVerticalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDiaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnGoiTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnDoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnLoaiHinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(pnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(pnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnGoiTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(pnVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(pnDoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addComponent(pnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(pnLoaiHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnTourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTourMouseEntered
        pnTour.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnTourMouseEntered

    private void pnTourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTourMouseExited
        pnTour.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnTourMouseExited

    private void pnGoiTourMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnGoiTourMouseEntered
        pnGoiTour.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnGoiTourMouseEntered

    private void pnDichVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDichVuMouseEntered
       pnDichVu.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnDichVuMouseEntered

    private void pnKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKhachHangMouseEntered
        pnKhachHang.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnKhachHangMouseEntered

    private void pnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNhanVienMouseEntered
        pnNhanVien.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnNhanVienMouseEntered

    private void pnDoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDoanMouseEntered
       pnDoan.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnDoanMouseEntered

    private void pnDiaDiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDiaDiemMouseEntered
        pnDiaDiem.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnDiaDiemMouseEntered

    private void pnVaiTroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnVaiTroMouseEntered
       pnVaiTro.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnVaiTroMouseEntered

    private void pnLoaiHinhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLoaiHinhMouseEntered
       pnLoaiHinh.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnLoaiHinhMouseEntered

    private void pnGoiTourMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnGoiTourMouseExited
       pnGoiTour.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnGoiTourMouseExited

    private void pnDichVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDichVuMouseExited
       pnDichVu.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnDichVuMouseExited

    private void pnKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKhachHangMouseExited
       pnKhachHang.setBackground(new Color(44,59,66));  // TODO add your handling code here:
    }//GEN-LAST:event_pnKhachHangMouseExited

    private void pnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNhanVienMouseExited
       pnNhanVien.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnNhanVienMouseExited

    private void pnDoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDoanMouseExited
        pnDoan.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnDoanMouseExited

    private void pnDiaDiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDiaDiemMouseExited
        pnDiaDiem.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnDiaDiemMouseExited

    private void pnVaiTroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnVaiTroMouseExited
        pnVaiTro.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnVaiTroMouseExited

    private void pnLoaiHinhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLoaiHinhMouseExited
        pnLoaiHinh.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnLoaiHinhMouseExited

    private void pnTourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTourMousePressed
        // TODO add your handling code here:
        new QuanLyTourGUI().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_pnTourMousePressed

    private void pnKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKhachHangMousePressed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new QuanLyKhachHangGUI().setVisible(true);
        
        
    }//GEN-LAST:event_pnKhachHangMousePressed

    private void pnGoiTourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnGoiTourMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new QuanLyGoiTourGUI().setVisible(true);
    }//GEN-LAST:event_pnGoiTourMousePressed

    private void pnDichVuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDichVuMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new QuanLyDichVuGUI().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnDichVuMousePressed

    private void pnDiaDiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDiaDiemMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new QuanLyDiaDiemGUI().setVisible(true);
    }//GEN-LAST:event_pnDiaDiemMousePressed

    private void pnNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNhanVienMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new QuanLyNhanVienGUI().setVisible(true);
    }//GEN-LAST:event_pnNhanVienMousePressed

    private void pnVaiTroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnVaiTroMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new QuanLyVaiTroNhanVien().setVisible(true);
    }//GEN-LAST:event_pnVaiTroMousePressed

    private void pnDoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnDoanMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        new QuanLyDoanGUI().setVisible(true);
    }//GEN-LAST:event_pnDoanMousePressed

    private void pnLoaiHinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnLoaiHinhMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new QuanLyLoaiHinhDuLichGUI().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnLoaiHinhMousePressed
    
    int mx , my;
    
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-mx-7, y-my-30);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        mx = evt.getX();
        my = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void pnThongKeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThongKeMouseEntered
        // TODO add your handling code here:
        pnThongKe.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnThongKeMouseEntered

    private void pnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThongKeMouseExited
        // TODO add your handling code here:
        pnThongKe.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnThongKeMouseExited

    private void pnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThongKeMousePressed
        // TODO add your handling code here:
        new ThongKeTheoTour().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnThongKeMousePressed

    private void pnTimKiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTimKiemMouseEntered
         pnTimKiem.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnTimKiemMouseEntered

    private void pnThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThoatMouseEntered
        pnThoat.setBackground(new Color(62,80,88));
    }//GEN-LAST:event_pnThoatMouseEntered

    private void pnTimKiemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTimKiemMouseExited
        pnTimKiem.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnTimKiemMouseExited

    private void pnThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThoatMouseExited
        pnThoat.setBackground(new Color(44,59,66));
    }//GEN-LAST:event_pnThoatMouseExited

    private void pnThoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThoatMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnThoatMousePressed

    private void pnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_pnThoatMouseClicked

    private void pnTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnTimKiemMouseClicked
        new TimKiem().setVisible(true);
        dispose();
    }//GEN-LAST:event_pnTimKiemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbDiaDiem;
    private javax.swing.JLabel lbDichVu;
    private javax.swing.JLabel lbDoan;
    private javax.swing.JLabel lbGoiTour;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbLoaiHinh;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbThoat;
    private javax.swing.JLabel lbThongKe;
    private javax.swing.JLabel lbTimKiem;
    private javax.swing.JLabel lbTour;
    private javax.swing.JLabel lbVaiTro;
    private javax.swing.JPanel pnDiaDiem;
    private javax.swing.JPanel pnDichVu;
    private javax.swing.JPanel pnDoan;
    private javax.swing.JPanel pnGoiTour;
    private javax.swing.JPanel pnKhachHang;
    private javax.swing.JPanel pnLoaiHinh;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnThoat;
    private javax.swing.JPanel pnThongKe;
    private javax.swing.JPanel pnTimKiem;
    private javax.swing.JPanel pnTour;
    private javax.swing.JPanel pnVaiTro;
    // End of variables declaration//GEN-END:variables
}
