/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.form;

import BLL.DiaDiemBLL;
import BLL.TinhBLL;
import DTO.DiaDiemDTO;
import DTO.TinhDTO;
import com.mycompany.util.DiaDiemTableLoaderUtil;
import com.mycompany.util.InputValidatorUtil;
import com.mycompany.util.TableSetupUtil;
import com.mycompany.util.VaiTroTableLoaderUtil;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Trieu
 */
public class QuanLyDiaDiemGUI extends javax.swing.JFrame {

    DiaDiemBLL ddb = new DiaDiemBLL();
    TinhBLL tb = new TinhBLL();
    List<TinhDTO> list;
    TableRowSorter<TableModel> rowSorter = null;
    String[] listColumns = {
                            "Mã địa điểm",
                            "Tên địa điểm",
                            "Tên tỉnh",
                            "Địa chỉ",
                            "Giới thiệu"};
    public QuanLyDiaDiemGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        loadTableData();
        loadTinh();
        txtTenDiaDiem.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtTenDiaDiem.getText().trim().length() == 50 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
            }
        });
        txtDiaChi.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtDiaChi.getText().trim().length() == 50 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
            }
        });
        txtGioiThieu.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtGioiThieu.getText().trim().length() == 50 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
            }
        });
        txtTimKiem.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtTimKiem.getText().trim().length() == 8 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    }               
                if (String.valueOf(evt.getKeyChar()).matches("[^A-Za-z0-9 /]")) {
                    evt.consume();
                }
            }
        });
    }
public void loadTableData(){
        tblDiaDiem.setModel(new DiaDiemTableLoaderUtil().setTable(ddb.findAll(), this.listColumns));
        this.rowSorter = TableSetupUtil.setTableFilter(tblDiaDiem, txtTimKiem);
    }
public void loadTinh(){
    list = tb.findAll();
    for(TinhDTO t : list){
        cbTinh.addItem(t.getMaTinh()+":"+t.getTenTinh());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiaDiem = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTenDiaDiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTinh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGioiThieu = new javax.swing.JTextArea();
        btnSua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMaDiaDiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTimKiem.setToolTipText("");

        tblDiaDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ ĐỊA ĐIỂM", "TÊN ĐỊA ĐIỂM", "TÊN TỈNH", "ĐỊA CHỈ", "GIỚI THIỆU"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDiaDiem.getTableHeader().setReorderingAllowed(false);
        tblDiaDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiaDiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDiaDiem);
        if (tblDiaDiem.getColumnModel().getColumnCount() > 0) {
            tblDiaDiem.getColumnModel().getColumn(3).setResizable(false);
            tblDiaDiem.getColumnModel().getColumn(4).setResizable(false);
        }

        btnThem.setText("THÊM ĐỊA ĐIỂM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(153, 0, 0));
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("QUẢN LÝ ĐỊA ĐIỂM");

        jButton3.setText("BACK");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jLabel2.setText("TÊN ĐỊA ĐIỂM");

        jLabel3.setText("TỈNH");

        jLabel4.setText("ĐỊA CHỈ");

        jLabel5.setText("GIỚI THIỆU");

        txtGioiThieu.setColumns(20);
        txtGioiThieu.setRows(5);
        jScrollPane2.setViewportView(txtGioiThieu);

        btnSua.setText("SỬA ĐỊA ĐIỂM");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel6.setText("MÃ ĐỊA ĐIỂM");

        txtMaDiaDiem.setEditable(false);

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenDiaDiem)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDiaChi)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19)))
                    .addComponent(jLabel6)
                    .addComponent(txtMaDiaDiem))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenDiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(cbTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3MousePressed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       int i = tblDiaDiem.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "Hay chon dong can sua !");

        } else if (txtTenDiaDiem.getText().isBlank() || txtDiaChi.getText().isBlank() || txtGioiThieu.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Hay nhap day du thong tin !");
        }  else if (!InputValidatorUtil.isValidName(txtTenDiaDiem.getText(), true).isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ten dia diem khong hop le");
        } else if (!InputValidatorUtil.isValidAddress(txtDiaChi.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Dia chi khong khong hop le");
        } else if (!InputValidatorUtil.isValidAddress(txtGioiThieu.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Gioi thieu khong khong hop le");
        } else {
            DiaDiemDTO d = new DiaDiemDTO();
            d.setMaDiaDiem(Integer.parseInt(txtMaDiaDiem.getText()));
            d.setMaTinh(Integer.parseInt(String.valueOf(cbTinh.getSelectedItem()).split(":")[0]));
            d.setTenDiaDiem(txtTenDiaDiem.getText());
            d.setDiaChi(txtDiaChi.getText());
            d.setGioiThieu(txtGioiThieu.getText());
            ddb.update(d);
            JOptionPane.showMessageDialog(rootPane, "Da sua dia diem");
            loadTableData();
            resetForm();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (txtTenDiaDiem.getText().isBlank() || txtDiaChi.getText().isBlank() || txtGioiThieu.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Hay nhap day du thong tin !");
        }else if (!InputValidatorUtil.isValidName(txtTenDiaDiem.getText(), true).isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ten dia diem khong hop le");
        } else if (!InputValidatorUtil.isValidAddress(txtDiaChi.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Dia chi khong khong hop le");
        } else if (!InputValidatorUtil.isValidAddress(txtGioiThieu.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Gioi thieu khong khong hop le");
        } else {
            DiaDiemDTO d = new DiaDiemDTO();
            d.setMaTinh(Integer.parseInt(String.valueOf(cbTinh.getSelectedItem()).split(":")[0]));
            d.setTenDiaDiem(txtTenDiaDiem.getText());
            d.setDiaChi(txtDiaChi.getText());
            d.setGioiThieu(txtGioiThieu.getText());
            ddb.save(d);
            JOptionPane.showMessageDialog(rootPane, "Da them dia diem");
            loadTableData();
            resetForm();
        }
        
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblDiaDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiaDiemMouseClicked
        int i = tblDiaDiem.getSelectedRow();
        txtMaDiaDiem.setText(String.valueOf(tblDiaDiem.getValueAt(i, 0)));
        txtTenDiaDiem.setText(String.valueOf(tblDiaDiem.getValueAt(i, 1)));
        txtDiaChi.setText(String.valueOf(tblDiaDiem.getValueAt(i, 3)));
        txtGioiThieu.setText(String.valueOf(tblDiaDiem.getValueAt(i, 4)));
        DiaDiemDTO d = ddb.findById(Integer.parseInt(String.valueOf(tblDiaDiem.getValueAt(i, 0))));
        cbTinh.setSelectedItem(d.getMaTinh()+":"+String.valueOf(tblDiaDiem.getValueAt(i, 2)));
    }//GEN-LAST:event_tblDiaDiemMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
       if(!(tblDiaDiem.getSelectedRow()<0)){
           int row = tblDiaDiem.getSelectedRow();
           int ma = Integer.parseInt(String.valueOf(tblDiaDiem.getValueAt(row, 0)));
            int conf = JOptionPane.showConfirmDialog(rootPane, "Thao tac se xoa dia diem nay khoi tat ca Tour neu co ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (conf == JOptionPane.YES_OPTION) {
               ddb.delete(ma);  //xoa dia diem
               ddb.delete_dsdd(ma); //xoa khoi dsdd_tour
               JOptionPane.showMessageDialog(rootPane, "Xoa thanh cong");
               loadTableData();
               resetForm();
            }
       }else{
           JOptionPane.showMessageDialog(rootPane, "Hay chon dia diem can xoa !");
       }
    }//GEN-LAST:event_btnXoaActionPerformed
    public void resetForm(){
        txtMaDiaDiem.setText("");
        txtTenDiaDiem.setText("");
        txtDiaChi.setText("");
        txtGioiThieu.setText("");
        cbTinh.setSelectedIndex(0);
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbTinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDiaDiem;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextArea txtGioiThieu;
    private javax.swing.JTextField txtMaDiaDiem;
    private javax.swing.JTextField txtTenDiaDiem;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
