/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.form;

import BLL.LoaiHinhDuLichBLL;
import DTO.LoaiHinhDuLichDTO;
import com.mycompany.util.InputValidatorUtil;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trieu
 */
public class QuanLyLoaiHinhDuLichGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyLoaiHinhDuLichGUI
     */
    public static ArrayList<LoaiHinhDuLichDTO> listdv = new ArrayList<>();
    public static DefaultTableModel modelloaihinhdulich;

    public QuanLyLoaiHinhDuLichGUI() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        modelloaihinhdulich = (DefaultTableModel) tblLoaiHinhDuLich.getModel();
        LocListLHDL();
        txtTenLoaiHinhDuLich.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtTenLoaiHinhDuLich.getText().trim().length() == 30 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiHinhDuLich = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        lblMaTour1 = new javax.swing.JLabel();
        txtMaLoaiHinhDuLich = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        txtTenLoaiHinhDuLich = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        lblTenLoaiHinhDuLich = new javax.swing.JLabel();
        lblMaLoaiHinhDuLich = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLoaiHinhDuLich.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÊN LOẠI HÌNH DU LỊCH", "SỐ TOUR HIỆN CÓ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiHinhDuLich.getTableHeader().setReorderingAllowed(false);
        tblLoaiHinhDuLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLoaiHinhDuLichMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiHinhDuLich);

        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        lblMaTour1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblMaTour1.setText("QUẢN LÝ LOẠI HÌNH DU LỊCH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(lblMaTour1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblMaTour1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtMaLoaiHinhDuLich.setEditable(false);

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(204, 0, 0));
        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        lblTenLoaiHinhDuLich.setText("TÊN LOẠI HÌNH DU LỊCH");

        lblMaLoaiHinhDuLich.setText("MÃ LOẠI HÌNH DU LỊCH");

        jButton2.setText("RESET");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaLoaiHinhDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaLoaiHinhDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenLoaiHinhDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenLoaiHinhDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMaLoaiHinhDuLich)
                .addGap(6, 6, 6)
                .addComponent(txtMaLoaiHinhDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblTenLoaiHinhDuLich)
                .addGap(6, 6, 6)
                .addComponent(txtTenLoaiHinhDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        try {
            // TODO add your handling code here:
            ResetTxt();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyLoaiHinhDuLichGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MousePressed

    private void tblLoaiHinhDuLichMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiHinhDuLichMousePressed
        // TODO add your handling code here:
        int i = tblLoaiHinhDuLich.getSelectedRow();
        if (i >= 0) {
            txtMaLoaiHinhDuLich.setText(String.valueOf(modelloaihinhdulich.getValueAt(i, 0)));
            txtTenLoaiHinhDuLich.setText(String.valueOf(modelloaihinhdulich.getValueAt(i, 1)));
        }
    }//GEN-LAST:event_tblLoaiHinhDuLichMousePressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
         if (txtMaLoaiHinhDuLich.getText().isEmpty()) {
            if (txtTenLoaiHinhDuLich.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Chua nhap du thong tin");
            }        
           else if(!InputValidatorUtil.isValidName(txtTenLoaiHinhDuLich.getText(), true).isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Ten loai hinh du lich khong hop le");
        }
            
            else {
                LoaiHinhDuLichDTO dv = new LoaiHinhDuLichDTO();
                
                dv.setTenLoaiDuLich(txtTenLoaiHinhDuLich.getText());

                if (new LoaiHinhDuLichBLL().themLoaiHinhDuLich(dv)) {
                    try {
                        JOptionPane.showMessageDialog(rootPane, "Da them");
                        ResetTxt();
                        LocListLHDL();
                    } catch (SQLException ex) {
                        Logger.getLogger(QuanLyLoaiHinhDuLichGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    //JOptionPane.showMessageDialog(rootPane,)

                    JOptionPane.showMessageDialog(rootPane, "ERROR");
                }
            }
        } else {
            try {
                JOptionPane.showMessageDialog(rootPane, "Trùng mã");
                ResetTxt();
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyLoaiHinhDuLichGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
          int i = tblLoaiHinhDuLich.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "Chon dong can thuc hien");
        } else {
            if (txtMaLoaiHinhDuLich.getText().isEmpty() || txtTenLoaiHinhDuLich.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Chua nhap du thong tin");
            } 
            else if(!InputValidatorUtil.isValidName(txtTenLoaiHinhDuLich.getText(), true).isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Ten loai hinh du lich khong hop le");
        }
            
            
            else {

                //DichVuDTO dv = new DichVuDTO();
                int Ma = Integer.parseInt(String.valueOf(txtMaLoaiHinhDuLich.getText()));
                String Ten = txtTenLoaiHinhDuLich.getText();
                int conf = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn sửa TOUR này ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (conf == JOptionPane.YES_OPTION) {
                    if (new LoaiHinhDuLichBLL().suaLoaiHinhDuLich(Ma, Ten)) {
                        try {
                            JOptionPane.showMessageDialog(rootPane, "Sua thanh cong");
                            ResetTxt();
                            LocListLHDL();
                        } catch (SQLException ex) {
                            Logger.getLogger(QuanLyLoaiHinhDuLichGUI.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERROR");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         // TODO add your handling code here:
        int i = tblLoaiHinhDuLich.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "Chon dong can thuc hien");
        } else {
            if(Integer.parseInt(String.valueOf(tblLoaiHinhDuLich.getValueAt(tblLoaiHinhDuLich.getSelectedRow(), 2)))>0){
                JOptionPane.showMessageDialog(rootPane, "Khong xoa duoc vi loai hinh nay dang co Tour");
            }else{
                int Ma = Integer.parseInt(String.valueOf(txtMaLoaiHinhDuLich.getText()));
            String Ten = txtTenLoaiHinhDuLich.getText();
            int conf = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xoá "+ Ten+" ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (conf == JOptionPane.YES_OPTION) {
                if (new LoaiHinhDuLichBLL().xoaLoaiHinhDuLich(Ma)) {
                    try {
                        JOptionPane.showMessageDialog(rootPane, "Xoa thanh cong");
                        ResetTxt();
                        LocListLHDL();
                    } catch (SQLException ex) {
                        Logger.getLogger(QuanLyLoaiHinhDuLichGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERROR");
                }
            }
            }
            //DichVuDTO dv = new DichVuDTO();
            
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    public static void LocListLHDL() throws SQLException {
        modelloaihinhdulich.setRowCount(0);
        listdv = new LoaiHinhDuLichBLL().getAll();
        for (LoaiHinhDuLichDTO dv : listdv) {
            
            modelloaihinhdulich.addRow(new Object[]{dv.getMaLoaiDuLich(), dv.getTenLoaiDuLich() , new LoaiHinhDuLichBLL().goiSoLuongTour(dv.getMaLoaiDuLich())});
        }
    }

    public void ResetTxt() throws SQLException {
        txtMaLoaiHinhDuLich.setText("");
        txtTenLoaiHinhDuLich.setText("");

        LocListLHDL();
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaLoaiHinhDuLich;
    private javax.swing.JLabel lblMaTour1;
    private javax.swing.JLabel lblTenLoaiHinhDuLich;
    private javax.swing.JTable tblLoaiHinhDuLich;
    private javax.swing.JTextField txtMaLoaiHinhDuLich;
    private javax.swing.JTextField txtTenLoaiHinhDuLich;
    // End of variables declaration//GEN-END:variables
}
