/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.form;

import BLL.LoaiHinhDuLichBLL;
import BLL.TourBLL;
import DAL.LoaiHinhDuLichDAL;
import DAL.TourDAL;
import DTO.LoaiHinhDuLichDTO;
import DTO.TourDTO;
import com.mycompany.popup.PopUpDanhSachDiemDi;
import com.mycompany.util.InputValidatorUtil;
import com.mycompany.util.TableSetupUtil;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Trieu
 */
public class QuanLyTourGUI extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyTour
     */
    public static ArrayList<TourDTO> listtour = new ArrayList<>();
    public static DefaultTableModel modeltour;
    public static PopUpDanhSachDiemDi dsdd;
    public static int matour;
    public TableRowSorter<TableModel> rowSorter = null;
    TourBLL tb = new TourBLL();
    public QuanLyTourGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        modeltour = (DefaultTableModel) tblTour.getModel();
        cbLoaiHinhDuLich();
        LocListTour();
        txtTenTour.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtTenTour.getText().trim().length() == 30 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
            }
        });
        txtTimKiem.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtTimKiem.getText().trim().length() == 8 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    }               
                if (String.valueOf(evt.getKeyChar()).matches("[^A-Za-z0-9 -]")) {
                    evt.consume();
                }
            }
        });
    }

    public void cbLoaiHinhDuLich() {

        ArrayList<LoaiHinhDuLichDTO> list = new LoaiHinhDuLichBLL().getAll();
        for (LoaiHinhDuLichDTO dl : list) {
            cbLoaiHinhDuLich.addItem(dl.getTenLoaiDuLich());
        }
        cbLoaiHinhDuLich.setSelectedIndex(0);
    }

    public void LocListTour() {
        modeltour.setRowCount(0);
        listtour = new TourDAL().getList();
        for (TourDTO t : listtour) {
            modeltour.addRow(new Object[]{t.getMaTour(), t.getTenTour(), new LoaiHinhDuLichBLL().goitenLoaiHinhDuLich(t.getMaLoaiHinhDuLich())});
        }
        this.rowSorter = TableSetupUtil.setTableFilter(tblTour, txtTimKiem);
//        String test = new TourDAL().GoiTenLoaiHinhDuLich("1");
//        System.out.println("kq : " + test);
    }

    public void ResetTxt() {
        txtMaTour.setText("");
        cbLoaiHinhDuLich.setSelectedItem(null);
        txtTenTour.setText("");

        LocListTour();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTour = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnXem = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblMaTour = new javax.swing.JLabel();
        txtMaTour = new javax.swing.JTextField();
        lblLoaiHinhDuLich = new javax.swing.JLabel();
        cbLoaiHinhDuLich = new javax.swing.JComboBox<>();
        lblTenTour = new javax.swing.JLabel();
        txtTenTour = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÊN TOUR", "LOẠI HÌNH DU LỊCH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTour.getTableHeader().setReorderingAllowed(false);
        tblTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTourMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblTour);

        btnSua.setText("SỬA TOUR");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXem.setText("DANH SÁCH ĐIỂM ĐI");
        btnXem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemActionPerformed(evt);
            }
        });

        btnThem.setText("THÊM TOUR MỚI");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(255, 0, 0));
        btnXoa.setText("XÓA TOUR");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setText("QUẢN LÝ TOUR DU LỊCH");

        btnBack.setText("BACK");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBackMousePressed(evt);
            }
        });

        lblMaTour.setText("MÃ TOUR");

        txtMaTour.setEditable(false);

        lblLoaiHinhDuLich.setText("LOẠI HÌNH DU LỊCH");

        lblTenTour.setText("TÊN TOUR");

        jButton1.setText("RESET");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenTour)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblLoaiHinhDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cbLoaiHinhDuLich, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaTour)
                                .addGap(124, 124, 124))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(16, 16, 16)
                        .addComponent(lblMaTour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblLoaiHinhDuLich)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLoaiHinhDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblTenTour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnThem)
                        .addGap(26, 26, 26)
                        .addComponent(btnSua)
                        .addGap(33, 33, 33)
                        .addComponent(btnXoa)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMousePressed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        ResetTxt();
    }//GEN-LAST:event_jButton1MousePressed

    private void tblTourMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTourMousePressed
        // TODO add your handling code here:
        //idTour = (int) tblTour.getValueAt(tblTour.getSelectedRow(), 0);
//        int i = tblTour.getSelectedRow();
//        if (i >= 0) {
//            txtMaTour.setText(String.valueOf(modeltour.getValueAt(i, 0)));
//            txtTenTour.setText(String.valueOf(modeltour.getValueAt(i, 1)));
//            cbLoaiHinhDuLich.setSelectedItem(String.valueOf(modeltour.getValueAt(i, 2)));

            txtMaTour.setText(String.valueOf(tblTour.getValueAt(tblTour.getSelectedRow(), 0)));
            txtTenTour.setText(String.valueOf(tblTour.getValueAt(tblTour.getSelectedRow(), 1)));
            cbLoaiHinhDuLich.setSelectedItem(String.valueOf(tblTour.getValueAt(tblTour.getSelectedRow(), 2)));

       // }
    }//GEN-LAST:event_tblTourMousePressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (txtMaTour.getText().isEmpty()) {
            if (txtTenTour.getText().isEmpty() || cbLoaiHinhDuLich.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(rootPane, "Chua nhap du thong tin");
            }
         else if(!InputValidatorUtil.isValidName(txtTenTour.getText(), true).isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Ten tour khong hop le");
        }
            
            else {
                TourDTO dv = new TourDTO();
                
                dv.setMaLoaiHinhDuLich(new LoaiHinhDuLichBLL().goimaLoaiHinhDuLich(String.valueOf(cbLoaiHinhDuLich.getSelectedItem())));
                dv.setTenTour(txtTenTour.getText());
                if (new TourBLL().themTour(dv)) {
                    JOptionPane.showMessageDialog(rootPane, "Da them");
                    ResetTxt();
                    LocListTour();
                } else {
                    //JOptionPane.showMessageDialog(rootPane,)
                    JOptionPane.showMessageDialog(rootPane, cbLoaiHinhDuLich.getSelectedItem());
                    JOptionPane.showMessageDialog(rootPane, "ERROR");
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Trùng mã");
            ResetTxt();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int i = tblTour.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "Chon dong can thuc hien");
        } else {
            if (txtMaTour.getText().isEmpty() || txtTenTour.getText().isEmpty() || cbLoaiHinhDuLich.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(rootPane, "Chua nhap du thong tin");
            } 
              else if(!InputValidatorUtil.isValidName(txtTenTour.getText(), true).isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Ten tour khong hop le");
        }
            
            else {

                //DichVuDTO dv = new DichVuDTO();
                int MaTour = Integer.parseInt(String.valueOf(txtMaTour.getText()));
                String TenTour = txtTenTour.getText();
                String TenLoaiDL = cbLoaiHinhDuLich.getSelectedItem().toString();
                int MaLoaiDL = new LoaiHinhDuLichBLL().goimaLoaiHinhDuLich(TenLoaiDL);
                int conf = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn sửa TOUR này ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (conf == JOptionPane.YES_OPTION) {
                    if (new TourBLL().suaTour(MaTour, TenTour, MaLoaiDL)) {
                        JOptionPane.showMessageDialog(rootPane, "Sua thanh cong");
                        ResetTxt();
                        LocListTour();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "ERROR");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemActionPerformed
       

        if (tblTour.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Chon dong can thuc hien");
        } else {
            matour = Integer.parseInt(String.valueOf(txtMaTour.getText()));
            System.out.println(matour);
            dsdd = new PopUpDanhSachDiemDi();
            dsdd.setVisible(true);
            
        }
    }//GEN-LAST:event_btnXemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int i = tblTour.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "Chon dong can thuc hien");
        } else {
           
               int idtour = Integer.parseInt(String.valueOf(tblTour.getValueAt(tblTour.getSelectedRow(),0)));
               if(tb.cotrongDoan(idtour)){
                   JOptionPane.showMessageDialog(rootPane, "Khong the xoa vi Tour nay dang ton tai it nhat trong 1 doan");
               }else{
                   int conf = JOptionPane.showConfirmDialog(rootPane, "Thao tac nay se xoa tat ca goi gia tour lien quan ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (conf == JOptionPane.YES_OPTION) {
               tb.xoaTour(idtour);
               JOptionPane.showMessageDialog(rootPane, "Xoa thanh cong");
               LocListTour();
               ResetTxt();
            }
               }
               
               
               
               
            
            
            //DichVuDTO dv = new DichVuDTO();
            
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbLoaiHinhDuLich;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoaiHinhDuLich;
    private javax.swing.JLabel lblMaTour;
    private javax.swing.JLabel lblTenTour;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTour;
    private javax.swing.JTextField txtMaTour;
    private javax.swing.JTextField txtTenTour;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
