/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.popup;

import BLL.VaiTroBLL;
import DTO.VaiTroDTO;
import com.mycompany.util.InputValidatorUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Trieu
 */
public class PopUpVaiTro extends javax.swing.JFrame {

    private String action;
    private VaiTroDTO vaiTro = null;
    private VaiTroBLL vaiTroBLL;
    
    public PopUpVaiTro() {
        initComponents();
        
    }

    public PopUpVaiTro(String action) {

        initComponents();
        this.action = action;
        vaiTroBLL = new VaiTroBLL();
        setLocationRelativeTo(null);
        this.setVisible(true);
        btnCapNhat.setText("Thêm");
        txtTenVaiTro.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtTenVaiTro.getText().trim().length() == 30 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
            }
        });
    }

    public PopUpVaiTro(String action, VaiTroDTO vaiTro) {
        initComponents();
        this.action = action;
        this.vaiTro = vaiTro;
        vaiTroBLL = new VaiTroBLL();
         setLabelText(vaiTro);
        this.setVisible(true);
        setLocationRelativeTo(null);
        btnCapNhat.setText("Lưu");
        txtTenVaiTro.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtTenVaiTro.getText().trim().length() == 30 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
            }
        });
    }

    public void setLabelText(VaiTroDTO vaiTro) {
        txtTenVaiTro.setText(vaiTro.getTenVaiTro());

    }

    private VaiTroDTO getFormInfo() {
        VaiTroDTO vaiTro = new VaiTroDTO();
        if (this.vaiTro != null) {
            vaiTro.setMaVaiTro(this.vaiTro.getMaVaiTro());
        }
        vaiTro.setTenVaiTro(txtTenVaiTro.getText().trim());
        return vaiTro;
    }

    public void center() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }
    public boolean validateForm() 
    {
         ImageIcon iconCheck = new ImageIcon("check.png");
        ImageIcon iconError = new ImageIcon("error.png");
        boolean tenVaiTro = false;

       if(InputValidatorUtil.isValidName(txtTenVaiTro.getText(), true).isEmpty())
       {
           lblValidateTenVaiTro.setIcon(iconCheck);
           lblValidateTenVaiTro.setToolTipText(null);
           tenVaiTro =  true;
           if(this.action.equals("POST")){
               if(vaiTroBLL.findByTenVaiTro(txtTenVaiTro.getText().trim())!=null){
                   tenVaiTro = false;
                   lblValidateTenVaiTro.setIcon(iconError);
                   lblValidateTenVaiTro.setToolTipText("Ten vai tro nay da ton tai");
               }
           } else if(this.action.equals("PUT")){
               VaiTroDTO newVaiTro = vaiTroBLL.findByTenVaiTro(txtTenVaiTro.getText().trim());
               if(newVaiTro != null){
                   if(newVaiTro.getMaVaiTro() != this.vaiTro.getMaVaiTro()){
                       tenVaiTro  =false;
                       lblValidateTenVaiTro.setIcon(iconError);
                       lblValidateTenVaiTro.setToolTipText("Ten vai tro nay da ton tai");
                   }
               }
           }
       }
       else {
           lblValidateTenVaiTro.setIcon(iconError);
           lblValidateTenVaiTro.setToolTipText(InputValidatorUtil.isValidName(txtTenVaiTro.getText(), true));
          tenVaiTro =  false;
       }
       
       
         if (tenVaiTro) {
            return true;
        } else {
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTenVaiTro = new javax.swing.JLabel();
        txtTenVaiTro = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        lblValidateTenVaiTro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTenVaiTro.setText("TÊN VAI TRÒ");

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CẬP NHẬT VAI TRÒ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidateTenVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(lblTenVaiTro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenVaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValidateTenVaiTro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
          if (validateForm()) {
            VaiTroDTO vaiTro = getFormInfo();

            if (this.action.equals("POST")) {
                Long newVaiTroId = vaiTroBLL.save(vaiTro);
                if (newVaiTroId != null) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bại!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            } else if (this.action.equals("PUT")) {
                try {
                    vaiTroBLL.update(vaiTro);
                    JOptionPane.showMessageDialog(this, "Lưu thành công!!!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lưu thất bại!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            }
        }
        
    }//GEN-LAST:event_btnCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTenVaiTro;
    private javax.swing.JLabel lblValidateTenVaiTro;
    private javax.swing.JTextField txtTenVaiTro;
    // End of variables declaration//GEN-END:variables
}
