/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.popup;

import BLL.DichVuBLL;
import BLL.GoiTourBLL;
import DTO.DichVuDTO;
import DTO.GoiTourDTO;
import com.mycompany.form.QuanLyGoiTourGUI;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trieu
 */
public class PopUpSuaThongTinGoi extends javax.swing.JFrame {

    GoiTourBLL gb = new GoiTourBLL();
    DefaultTableModel modeldichvu;
    ArrayList<DichVuDTO> listdv = new ArrayList<>();
    DichVuBLL dv = new DichVuBLL();
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    public PopUpSuaThongTinGoi() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        modeldichvu = (DefaultTableModel) tblThongTinGoi.getModel();
        setUp();
        try {
            LocListDV();
        } catch (SQLException ex) {
            Logger.getLogger(PopUpSuaThongTinGoi.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblThongTinGoi.getModel().addTableModelListener(new TableModelListener() {
            
            public void tableChanged(TableModelEvent e) {
                TinhGiaTongDV();
            }
        });
        txtGiaTour.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtGiaTour.getText().trim().length() == 8 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongTinGoi = new javax.swing.JTable();
        lblGiaTour = new javax.swing.JLabel();
        txtGiaTour = new javax.swing.JTextField();
        btnLuu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTong = new javax.swing.JTextField();
        lblChonTour = new javax.swing.JLabel();
        txtTenTour = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setText("SỬA THÔNG TIN TOUR TRỌN GÓI");

        tblThongTinGoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "TÊN DỊCH VỤ", "GIÁ TIỀN", "CHỌN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblThongTinGoi);

        lblGiaTour.setText("GIÁ TOUR CƠ BẢN");

        txtGiaTour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaTourKeyReleased(evt);
            }
        });

        btnLuu.setText("LƯU");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel3.setText("TỔNG CHI PHÍ GÓI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setText("GIÁ GÓI = TỔNG TIỀN DV + GIÁ TOUR CƠ BẢN");

        txtTong.setEditable(false);

        lblChonTour.setText("TOUR");

        txtTenTour.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblChonTour)
                            .addComponent(txtGiaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGiaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChonTour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblGiaTour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGiaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(txtGiaTour.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Hay nhap gia co ban !");
        }else{
            GoiTourDTO dt = gb.timGoiTour(QuanLyGoiTourGUI.idgiatour);
        if(gb.xoaDSDV(dt.getMaGiaTour())){
            if(gb.thaydoiGiaCoBan(dt.getMaGiaTour(), Double.parseDouble(txtGiaTour.getText()))){
                ArrayList<Integer> chondv = new ArrayList<>();
        for (int i = 0; i < tblThongTinGoi.getRowCount(); i++) {
            if ((Boolean) modeldichvu.getValueAt(i, 3)) {
                chondv.add(Integer.parseInt(String.valueOf(modeldichvu.getValueAt(i, 0))));
            }
        }
        
            gb.themDSDV_Tour(dt.getMaGiaTour(), chondv);
                JOptionPane.showMessageDialog(rootPane, "Da luu thay doi");
                dispose();
        
            }else{
                JOptionPane.showMessageDialog(rootPane,"Thay doi gia co ban that bai");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Xoa danhsach dich vu that bai");
        }
        }
        
    }//GEN-LAST:event_btnLuuActionPerformed

    private void txtGiaTourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaTourKeyReleased
        TinhGiaTongDV();
    }//GEN-LAST:event_txtGiaTourKeyReleased
    public void TinhGiaTongDV() {
        double tong;
        if(txtGiaTour.getText().isBlank()){
            tong=0;
        }
        else{
            tong=Double.parseDouble(txtGiaTour.getText());
        }
        
            for (int i = 0; i < tblThongTinGoi.getRowCount(); i++) {
                if ((Boolean) modeldichvu.getValueAt(i, 3)) {
                    tong += Double.parseDouble(String.valueOf(modeldichvu.getValueAt(i, 2)).replace(",", ""));
                } else {
                    tong += 0;
                }
            }
            txtTong.setText(String.valueOf(formatter.format(tong)));
        
        
    }
    public void setUp() {
        GoiTourDTO dt = gb.timGoiTour(QuanLyGoiTourGUI.idgiatour);
        txtTenTour.setText(gb.GoiTenTour(dt.getMaTour()));
        txtGiaTour.setText(String.valueOf((long)dt.getGiaCoBan()));
        txtTong.setText(String.valueOf(formatter.format((long)(dt.getGiaCoBan()+gb.TongGiaDV(dt.getMaGiaTour())))));
    }

    public void LocListDV() throws SQLException {
        modeldichvu.setRowCount(0);
        listdv = dv.getAll("1", "MaDichVu ASC");
        ArrayList<Integer> dsdv = gb.layDSDV(QuanLyGoiTourGUI.idgiatour);
        for (DichVuDTO dv : listdv) {
            modeldichvu.addRow(new Object[]{dv.getMaDV(), dv.getTenDV(), String.valueOf(formatter.format(dv.getGiaDV())), kiemtratontai(dv.getMaDV(), dsdv)});
        }
    }
    public boolean kiemtratontai(int iddv, ArrayList<Integer> dsdv) {
        for (int a : dsdv) {
            if (a == iddv) {
                return true;         
            }

        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChonTour;
    private javax.swing.JLabel lblGiaTour;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblThongTinGoi;
    private javax.swing.JTextField txtGiaTour;
    private javax.swing.JTextField txtTenTour;
    private javax.swing.JTextField txtTong;
    // End of variables declaration//GEN-END:variables
}
