/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.popup;

import BLL.DichVuBLL;
import BLL.DoanBLL;
import BLL.GoiTourBLL;
import DTO.DichVuDTO;
import static com.mycompany.form.QuanLyDichVuGUI.modeldichvu;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trieu
 */
public class PopUpThemGiaTourTronGoi extends javax.swing.JFrame {
    
    ArrayList<String> listcbTour;
    ArrayList<Integer> chondv;
    ArrayList<DichVuDTO> listdv = new ArrayList<>();
    DoanBLL db = new DoanBLL();
    DichVuBLL dv = new DichVuBLL();
    GoiTourBLL gb = new GoiTourBLL();
    DefaultTableModel modeldichvu;    
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    public PopUpThemGiaTourTronGoi() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        modeldichvu = (DefaultTableModel) tblDichVuCoSan.getModel();
        fillCbTour();
        
        LocListDV();
        txtTongChiPhi.setText("0.0");
        tblDichVuCoSan.getModel().addTableModelListener(new TableModelListener() {
            
            public void tableChanged(TableModelEvent e) {
                TinhGiaTongDV();
            }
        });
        txtGiaTourCoBan.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtGiaTourCoBan.getText().trim().length() == 8 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
                if (!Character.isDigit(evt.getKeyChar())) {
                    evt.consume();
                }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDichVuCoSan = new javax.swing.JTable();
        lblChonTour = new javax.swing.JLabel();
        cbTour = new javax.swing.JComboBox<>();
        lblGiaTourCoBan = new javax.swing.JLabel();
        txtGiaTourCoBan = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        lblTongChiPhi = new javax.swing.JLabel();
        txtTongChiPhi = new javax.swing.JTextField();
        lblGiaGoi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setText("THÊM TOUR TRỌN GÓI");

        tblDichVuCoSan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÊN DỊCH VỤ", "GIÁ TIỀN", "CHỌN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichVuCoSan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDichVuCoSan);
        if (tblDichVuCoSan.getColumnModel().getColumnCount() > 0) {
            tblDichVuCoSan.getColumnModel().getColumn(3).setResizable(false);
            tblDichVuCoSan.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        lblChonTour.setText("CHỌN TOUR");

        cbTour.setEditable(true);

        lblGiaTourCoBan.setText("GIÁ TOUR CƠ BẢN");

        txtGiaTourCoBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGiaTourCoBanKeyReleased(evt);
            }
        });

        btnThem.setText("THÊM GÓI MỚI");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        lblTongChiPhi.setText("TỔNG CHI PHÍ GÓI");

        txtTongChiPhi.setEditable(false);
        txtTongChiPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongChiPhiActionPerformed(evt);
            }
        });

        lblGiaGoi.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblGiaGoi.setText("GIÁ GÓI = TỔNG TIỀN DỊCH VỤ + GIÁ TOUR CƠ BẢN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiaTourCoBan, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(lblGiaTourCoBan, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(lblChonTour, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGiaGoi, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTongChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(txtTongChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblChonTour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblGiaTourCoBan)
                        .addGap(18, 18, 18)
                        .addComponent(txtGiaTourCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnThem))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongChiPhi)
                    .addComponent(txtTongChiPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblGiaGoi)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongChiPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongChiPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongChiPhiActionPerformed
    public void TinhGiaTongDV() {
        double tong;
        if(txtGiaTourCoBan.getText().isBlank()){
            tong=0;
        }
        else{
            tong=Double.parseDouble(txtGiaTourCoBan.getText());
        }
        
            for (int i = 0; i < tblDichVuCoSan.getRowCount(); i++) {
                if ((Boolean) modeldichvu.getValueAt(i, 3)) {
                    tong += Double.parseDouble(String.valueOf(modeldichvu.getValueAt(i, 2)).replace(",", ""));
                } else {
                    tong += 0;
                }
            }
            txtTongChiPhi.setText(String.valueOf(formatter.format(tong)));
        
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if(txtGiaTourCoBan.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Hay nhap gia co ban !");
        }else{
            chondv = new ArrayList<>();
        for (int i = 0; i < tblDichVuCoSan.getRowCount(); i++) {
            if ((Boolean) modeldichvu.getValueAt(i, 3)) {
                chondv.add(Integer.parseInt(String.valueOf(modeldichvu.getValueAt(i, 0))));
            }
        }
        double giacoban = Double.parseDouble(txtGiaTourCoBan.getText());
        int matour = Integer.parseInt(String.valueOf(cbTour.getSelectedItem()).split(":")[0]);
        if(gb.themGoiTour(matour, giacoban)){
            int mavuatao = gb.magiatourVuathem();
            gb.themDSDV_Tour(mavuatao, chondv);
                JOptionPane.showMessageDialog(rootPane, "Da them mot goi gia Tour moi");
                dispose();
        }
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtGiaTourCoBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaTourCoBanKeyReleased
       TinhGiaTongDV();
    }//GEN-LAST:event_txtGiaTourCoBanKeyReleased
    public void fillCbTour() {
        cbTour.removeAllItems();
        listcbTour = db.fillCBTour();
        for (String s : listcbTour) {
            cbTour.addItem(s);
           
        }
    }

    public void LocListDV() throws SQLException {
        modeldichvu.setRowCount(0);
        listdv = dv.getAll("1", "MaDichVu ASC");
        for (DichVuDTO dv : listdv) {
            modeldichvu.addRow(new Object[]{dv.getMaDV(), dv.getTenDV(), String.valueOf(formatter.format(dv.getGiaDV())), false});
        }
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbTour;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChonTour;
    private javax.swing.JLabel lblGiaGoi;
    private javax.swing.JLabel lblGiaTourCoBan;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTongChiPhi;
    private javax.swing.JTable tblDichVuCoSan;
    private javax.swing.JTextField txtGiaTourCoBan;
    private javax.swing.JTextField txtTongChiPhi;
    // End of variables declaration//GEN-END:variables
}
