/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.popup;

import BLL.DoanBLL;
import BLL.VaiTroBLL;
import DTO.DoanDTO;
import DTO.KhachHangDTO;
import DTO.NhanVienDTO;
import com.mycompany.form.QuanLyDoanGUI;
import com.mycompany.util.TableSetupUtil;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trieu
 */
public class PopUpChiTietDoan extends javax.swing.JFrame {

    /**
     * Creates new form PopUpKhachNhanVienDoan
     */
    DoanBLL db = new DoanBLL();
    DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<KhachHangDTO> listKH;
    ArrayList<NhanVienDTO> listNV;
    VaiTroBLL vb = new VaiTroBLL();
    public PopUpChiTietDoan() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setupForm();
    }
    public void setupForm(){
        DoanDTO d = db.findDoanbyID(QuanLyDoanGUI.idDoan);      
        txtTenDoan.setText(d.getTenDoan());
        loadTableKH();
        loadTableNV();
    }
    public void loadTableKH(){
        listKH = db.listKH_Doan(QuanLyDoanGUI.idDoan);
        dtm = (DefaultTableModel) tblKhachDoan.getModel();
        dtm.setRowCount(0);
        for(KhachHangDTO kh:listKH){
            dtm.addRow(new Object[]{kh.getMaKH(),kh.getHoTen(),kh.getSDT()});
        }
       
    }
    public void loadTableNV(){
        listNV = db.listNV_Doan(QuanLyDoanGUI.idDoan);
        dtm = (DefaultTableModel) tblNhanVienDoan.getModel();
        dtm.setRowCount(0);
        for(NhanVienDTO nv:listNV){
            dtm.addRow(new Object[]{nv.getMaNhanVien(),nv.getHoTen(),vb.findById(nv.getMaVaiTro()).getTenVaiTro()});
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDSKhachDoan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachDoan = new javax.swing.JTable();
        btnThemKhachDoan = new javax.swing.JButton();
        btnXoaKhachDoan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblDSNVDoan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNhanVienDoan = new javax.swing.JTable();
        btnThemNVDoan = new javax.swing.JButton();
        btnXoaNVDoan = new javax.swing.JButton();
        txtTenDoan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        lblDSKhachDoan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDSKhachDoan.setText("DANH SÁCH KHÁCH HÀNG ĐOÀN");

        tblKhachDoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "HỌ TÊN KHÁCH HÀNG", "SĐT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachDoan.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblKhachDoan);

        btnThemKhachDoan.setText("THÊM KHÁCH HÀNG");
        btnThemKhachDoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThemKhachDoanMousePressed(evt);
            }
        });

        btnXoaKhachDoan.setText("XÓA KHÁCH HÀNG");
        btnXoaKhachDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhachDoanActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblDSNVDoan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblDSNVDoan.setText("DANH SÁCH NHÂN VIÊN ĐOÀN");

        tblNhanVienDoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "HỌ TÊN NHÂN VIÊN", "VAI TRÒ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVienDoan.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblNhanVienDoan);

        btnThemNVDoan.setText("THÊM NHÂN VIÊN");
        btnThemNVDoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThemNVDoanMousePressed(evt);
            }
        });

        btnXoaNVDoan.setText("XÓA NHÂN VIÊN");
        btnXoaNVDoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVDoanActionPerformed(evt);
            }
        });

        txtTenDoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenDoan.setText("jLabel3");

        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnThemKhachDoan)
                        .addGap(13, 13, 13)
                        .addComponent(btnXoaKhachDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblDSKhachDoan)))
                .addGap(32, 32, 32)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDSNVDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTenDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnThemNVDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnXoaNVDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(lblDSKhachDoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemKhachDoan)
                            .addComponent(btnXoaKhachDoan))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTenDoan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDSNVDoan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThemNVDoan)
                                    .addComponent(btnXoaNVDoan))
                                .addGap(12, 12, 12))
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemKhachDoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemKhachDoanMousePressed
        // TODO add your handling code here:
        new PopUpThemKhachHangDoan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThemKhachDoanMousePressed

    private void btnThemNVDoanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemNVDoanMousePressed
        // TODO add your handling code here:
        new PopUpThemNhanVienDoan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThemNVDoanMousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        new QuanLyDoanGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void btnXoaKhachDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhachDoanActionPerformed
        if(tblKhachDoan.getSelectedRow()<0){
            JOptionPane.showMessageDialog(rootPane, "Hay chon khach hang can xoa !");
        }else{
            int i = tblKhachDoan.getSelectedRow();
            int idkhach = Integer.parseInt(String.valueOf(tblKhachDoan.getValueAt(i, 0)));
            int iddoan = QuanLyDoanGUI.idDoan;
            if(db.xoaKHkhoiDoan(idkhach, iddoan)){
                JOptionPane.showMessageDialog(rootPane, "Da xoa khach hang!");
                
                loadTableKH();
            }else{
                 JOptionPane.showMessageDialog(rootPane, "Co loi xay ra");
            }
        }
    }//GEN-LAST:event_btnXoaKhachDoanActionPerformed

    private void btnXoaNVDoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVDoanActionPerformed
        if(tblNhanVienDoan.getSelectedRow()<0){
            JOptionPane.showMessageDialog(rootPane, "Hay chon nhan vien can xoa !");
        }else{
            int i = tblNhanVienDoan.getSelectedRow();
            int idnv = Integer.parseInt(String.valueOf(tblNhanVienDoan.getValueAt(i, 0)));
            int iddoan = QuanLyDoanGUI.idDoan;
            if(db.xoaNVkhoiDoan(idnv, iddoan)){
                JOptionPane.showMessageDialog(rootPane, "Da xoa nhan vien ");
                
                loadTableNV();
            }else{
                 JOptionPane.showMessageDialog(rootPane, "Co loi xay ra");
            }
        }
    }//GEN-LAST:event_btnXoaNVDoanActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemKhachDoan;
    private javax.swing.JButton btnThemNVDoan;
    private javax.swing.JButton btnXoaKhachDoan;
    private javax.swing.JButton btnXoaNVDoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDSKhachDoan;
    private javax.swing.JLabel lblDSNVDoan;
    private javax.swing.JTable tblKhachDoan;
    private javax.swing.JTable tblNhanVienDoan;
    private javax.swing.JLabel txtTenDoan;
    // End of variables declaration//GEN-END:variables
}
