/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.popup;

import BLL.DoanBLL;
import DTO.DoanDTO;
import com.mycompany.form.QuanLyDoanGUI;
import com.mycompany.util.InputValidatorUtil;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Trieu
 */
public class PopUpThemDoan extends javax.swing.JFrame {

    ArrayList<String> listcbTour;
    ArrayList<Integer> listcbGiaTour;
    DoanBLL db = new DoanBLL();
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    public PopUpThemDoan() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        fillCbTour();
        txtTenDoan.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent evt) {
                if (txtTenDoan.getText().trim().length() == 40 || evt.getKeyChar() == java.awt.event.KeyEvent.VK_BACK_SPACE) {
        evt.consume();
    } 
            }
        });
    }
    public void fillCbTour(){
        cbTour.removeAll();
        listcbTour = db.fillCBTour();
        for(String s : listcbTour){
            cbTour.addItem(s);
        }
    }
    public void fillCbGiaTour(int id){
//        String idtour = String.valueOf(cbTour.getSelectedItem());
//        String[] idtour2 = idtour.split(":");
        cbGiaTour.removeAll();
        listcbGiaTour = db.listMaGiaTour(id);
        for(int s: listcbGiaTour){
            cbGiaTour.addItem(+s+":"+String.valueOf(formatter.format(db.cal_GoiGiaTour(s, id))));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNgayBatDau = new javax.swing.JLabel();
        txtTenDoan = new javax.swing.JTextField();
        lblTour = new javax.swing.JLabel();
        lblTenDoan = new javax.swing.JLabel();
        cbGiaTour = new javax.swing.JComboBox<>();
        cbTour = new javax.swing.JComboBox<>();
        txtNgayBD = new com.toedter.calendar.JDateChooser();
        lblNgayKetThuc = new javax.swing.JLabel();
        lblGiaTour = new javax.swing.JLabel();
        txtNgayKT = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setText("HỦY");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("THÊM ĐOÀN");

        lblNgayBatDau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNgayBatDau.setText("NGÀY BẮT ĐẦU");

        lblTour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTour.setText("TOUR");

        lblTenDoan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTenDoan.setText("TÊN ĐOÀN");

        cbTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTourActionPerformed(evt);
            }
        });
        cbTour.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbTourPropertyChange(evt);
            }
        });

        lblNgayKetThuc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNgayKetThuc.setText("NGÀY KẾT THÚC");

        lblGiaTour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblGiaTour.setText("GIÁ TOUR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTour, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGiaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNgayBD, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(cbTour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbGiaTour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTenDoan)))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenDoan))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTour)
                                    .addComponent(cbTour, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGiaTour)
                                    .addComponent(cbGiaTour, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(lblNgayBatDau))
                            .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(lblNgayKetThuc))
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnHuy))
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if(txtTenDoan.getText().isBlank()||txtNgayBD.getDate()==null||txtNgayKT.getDate()==null||cbGiaTour.getSelectedItem()==null||cbTour.getSelectedItem()==null){
            JOptionPane.showMessageDialog(rootPane, "Hay nhap day du thong tin");
        } else if(!txtNgayKT.getDate().after(txtNgayBD.getDate())){
             JOptionPane.showMessageDialog(rootPane, "Ngay ket thuc phai giong hoac sau ngay bat dau");
        }
          else if(!InputValidatorUtil.isValidName(txtTenDoan.getText(), true).isEmpty()){
             JOptionPane.showMessageDialog(rootPane, "Ten doan khong hop le");
        }
        else{
            DoanDTO d = new DoanDTO();
        d.setTenDoan(txtTenDoan.getText());
        d.setIdTour(Integer.parseInt(String.valueOf(cbTour.getSelectedItem()).split(":")[0]));
        d.setIdGiaTour(Integer.parseInt(String.valueOf(cbGiaTour.getSelectedItem()).split(":")[0]));
        d.setNgayKH(txtNgayBD.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        d.setNgayKT(txtNgayKT.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        if(db.insert(d)){
            JOptionPane.showMessageDialog(rootPane, "Da them doan moi");
            txtTenDoan.setText("");
            fillCbTour();
            cbGiaTour.removeAll();
            txtNgayBD.setDate(null);
            txtNgayKT.setDate(null);
            
            dispose();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Co loi xay ra");
        }
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void cbTourPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbTourPropertyChange
        
    }//GEN-LAST:event_cbTourPropertyChange

    private void cbTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTourActionPerformed
        cbGiaTour.removeAllItems();
        String idtour = String.valueOf(cbTour.getSelectedItem());
        String[] idtour2 = idtour.split(":");
        fillCbGiaTour(Integer.parseInt(idtour2[0]));
    }//GEN-LAST:event_cbTourActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGioiTinh;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbGiaTour;
    private javax.swing.JComboBox<String> cbTour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGiaTour;
    private javax.swing.JLabel lblNgayBatDau;
    private javax.swing.JLabel lblNgayKetThuc;
    private javax.swing.JLabel lblTenDoan;
    private javax.swing.JLabel lblTour;
    private com.toedter.calendar.JDateChooser txtNgayBD;
    private com.toedter.calendar.JDateChooser txtNgayKT;
    private javax.swing.JTextField txtTenDoan;
    // End of variables declaration//GEN-END:variables
}
