/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.popup;

import BLL.DS_DiaDiemTourBLL;
import BLL.DiaDiemBLL;
import BLL.LoaiHinhDuLichBLL;
import BLL.TourBLL;
import DTO.DiaDiemDTO;
import DTO.TourDTO;
import com.mycompany.form.QuanLyTourGUI;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Trieu
 */
public class PopUpDanhSachDiemDi extends javax.swing.JFrame {

    /**
     * Creates new form PopUpDanhSachDiemDi
     */
    //JFrame frame;
    public static DefaultTableModel modeldsdd;
   

    public PopUpDanhSachDiemDi() {

        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        modeldsdd = (DefaultTableModel) tblDanhSachDiemDi.getModel();
        setTblDSDD();
        setCBdiadiem();
        setUp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachDiemDi = new javax.swing.JTable();
        cbDanhSachDiemDi = new javax.swing.JComboBox<>();
        lblTitle1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbMaTour = new javax.swing.JLabel();
        lbLoaiHinhDuLich = new javax.swing.JLabel();
        lbTenTour = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl1.setText("MÃ TOUR :");

        lbl2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl2.setText("LOẠI HÌNH DU LỊCH :");

        lbl3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl3.setText("TÊN TOUR :");

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setText("DANH SÁCH ĐIỂM ĐI");

        tblDanhSachDiemDi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "STT", "TÊN ĐỊA ĐIỂM - TỈNH"
            }
        ));
        jScrollPane1.setViewportView(tblDanhSachDiemDi);

        lblTitle1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitle1.setText("CHỌN DANH SÁCH ĐIỂM ĐI");

        btnThem.setText("THÊM");
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThemMousePressed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(153, 0, 0));
        btnXoa.setText("XÓA");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnXoaMousePressed(evt);
            }
        });

        lbMaTour.setText("jLabel1");

        lbLoaiHinhDuLich.setText("jLabel1");

        lbTenTour.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl2)
                        .addGap(18, 18, 18)
                        .addComponent(lbLoaiHinhDuLich)
                        .addGap(65, 552, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 11, Short.MAX_VALUE)
                                        .addComponent(cbDanhSachDiemDi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbMaTour))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTenTour)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl1)
                            .addComponent(lbMaTour))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl2)
                            .addComponent(lbLoaiHinhDuLich))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3)
                    .addComponent(lbTenTour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitle1)
                        .addGap(18, 18, 18)
                        .addComponent(cbDanhSachDiemDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMousePressed
        // TODO add your handling code here:
        String diadiem = String.valueOf(cbDanhSachDiemDi.getSelectedItem());
        if (diadiem.equals("---Chọn Địa Điểm---")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn địa điểm cần THÊM...");
        } else {
            ArrayList<String> list = new DS_DiaDiemTourBLL().getDSDiaDiem(QuanLyTourGUI.matour);
            int dem = 0;
            for (int i = 0; i < list.size(); i++) {
                if (diadiem.equals(list.get(i))) {
                    dem++;
                }
            }
            if(dem != 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Địa điểm này hiện ĐÃ có trong danh sách địa điểm ...");
            }
            else{
                int madiadiem = new DS_DiaDiemTourBLL().timMaDiaDiem(diadiem);
                if(new DS_DiaDiemTourBLL().themDS_DiaDiemTour(Integer.parseInt(lbMaTour.getText()), madiadiem)){
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công !");
                    setTblDSDD();
                    setCBdiadiem();
                }
                else{
                    JOptionPane.showMessageDialog(rootPane, "Thêm thất bại !");
                }
                
            }
        }

    }//GEN-LAST:event_btnThemMousePressed

    private void btnXoaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMousePressed
        // TODO add your handling code here:
        int i = tblDanhSachDiemDi.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(rootPane, "Chon dong can thuc hien");
        } else {
            int MaTour = Integer.parseInt(lbMaTour.getText());
            //int MaDiaDiem = Integer.parseInt()  ;
            int MaDiaDiem = new DS_DiaDiemTourBLL().timMaDiaDiem(String.valueOf(modeldsdd.getValueAt(i, 1)));
            
            
            int conf = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa TOUR này ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (conf == JOptionPane.YES_OPTION) {
                if (new DS_DiaDiemTourBLL().xoaDS_DiaDiemTour(MaTour,MaDiaDiem)) {
                    JOptionPane.showMessageDialog(rootPane, "Xoa thanh cong");
                    setTblDSDD();
                    setCBdiadiem();
                    
                } else {
                    JOptionPane.showMessageDialog(rootPane, "ERROR");
                }
            }
        }
    }//GEN-LAST:event_btnXoaMousePressed

    /**
     * @param args the command line arguments
     */
    
    public void setTblDSDD() {

        modeldsdd.setRowCount(0);

        //btnThemActionPerformed(java.awt.event.ActionEvent evt);
//        System.out.println(tour.matour);
//        System.out.println(lbLoaiHinhDuLich.getText());
//        System.out.println(lbTenTour.getText());
    
        ArrayList<String> list = new DS_DiaDiemTourBLL().getDSDiaDiem(QuanLyTourGUI.matour);

        for (int i = 0; i < list.size(); i++) {
            modeldsdd.addRow(new Object[]{i + 1, list.get(i)});
            //System.out.println((i + 1) + " /  " + list.get(i));
        }
        
        
    }

    public void setCBdiadiem() {
        List<DiaDiemDTO> list = new DiaDiemBLL().findAll();
        cbDanhSachDiemDi.addItem("---Chọn Địa Điểm---");

        for (DiaDiemDTO dd : list) {

            cbDanhSachDiemDi.addItem(dd.getTenDiaDiem());
        }
        
        cbDanhSachDiemDi.setSelectedIndex(0);
    }
    public void setUp(){
         TourDTO t = new TourBLL().getTour(QuanLyTourGUI.matour);
         lbMaTour.setText(String.valueOf(t.getMaTour()));
         lbTenTour.setText(t.getTenTour());
         lbLoaiHinhDuLich.setText(new LoaiHinhDuLichBLL().goitenLoaiHinhDuLich(t.getMaLoaiHinhDuLich())); 
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbDanhSachDiemDi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbLoaiHinhDuLich;
    public javax.swing.JLabel lbMaTour;
    public javax.swing.JLabel lbTenTour;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblDanhSachDiemDi;
    // End of variables declaration//GEN-END:variables
}
